# Generated by Django 2.1.7 on 2022-03-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=720, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1220, null=True)),
                ('size_in_kb', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=220, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
        migrations.CreateModel(
            name='OrdersDetails',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders_details',
            },
        ),
    ]
